name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build for linux
      run: | 
            go mod init cmd/main.go
            cd cmd/
            go mod tidy
            set GOOS=linux 
            set GOARCH=amd64 
            go build -o aws-explorer cmd/main.go 

    - name: Build for Windows
      run: | 
        go mod init cmd/main.go
        cd cmd/
        go mod tidy
        set GOOS=windows
        set GOARCH=amd64 
        go build -o aws-explorer.exe cmd/main.go 

    
