name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Initialize
      run: |
        go mod init cmd/main.go
        cd cmd/
        go mod tidy
    
    - name: Build for Linux
      run: | 
        cd cmd/
        set GOOS=linux 
        set GOARCH=amd64 
        go build -o aws-explorer-linux main.go

    - name: Build for MacOS
      run: | 
        cd cmd/
        set GOOS=darwin 
        set GOARCH=amd64 
        go build -o aws-explorer-mac main.go

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: cmd/aws-explorer

    - name: Upload Mac Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mac-artifact
        path: cmd/aws-explorer.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-artifact
        path: cmd/

    - name: Download Mac Artifact
      uses: actions/download-artifact@v4
      with:
        name: Mac-artifact
        path: cmd/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1
        release_name: Release v1
        draft: false
        prerelease: false

    - name: Check Linux Artifact
      run: |
        if [ ! -f cmd/aws-explorer ]; then
          echo "Linux artifact not found!"
          exit 1
        fi

    - name: Upload Linux Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cmd/aws-explorer
        asset_name: aws-explorer
        asset_content_type: application/octet-stream

    - name: Check Mac Artifact
      run: |
        if [ ! -f cmd/aws-explorer ]; then
          echo "Mac artifact not found!"
          exit 1
        fi

    - name: Upload Mac Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cmd/aws-explorer.exe
        asset_name: aws-explorer.exe
        asset_content_type: application/octet-stream