name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: intialize
      run: |
            go mod init cmd/main.go
            cd cmd/
            go mod tidy
    
    - name: Build for linux
      run: | 
            set GOOS=linux 
            set GOARCH=amd64 
            go build -o aws-explorer main.go 

    - name: Build for Windows
      run: | 
        cd cmd/
        set GOOS=windows
        set GOARCH=amd64 
        go build -o aws-explorer.exe main.go 

    
