name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: intialize
      run: |
            go mod init cmd/main.go
            cd cmd/
            go mod tidy
    
    - name: Build for linux
      run: | 
            cd cmd/
            set GOOS=linux 
            set GOARCH=amd64 
            go build -o aws-explorer main.go 

    - name: Build for Windows
      run: | 
        cd cmd/
        set GOOS=windows
        set GOARCH=amd64 
        go build -o aws-explorer.exe main.go

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Linux Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cmd/aws-explorer
        asset_name: aws-explorer
        asset_content_type: application/octet-stream

    - name: Upload Windows Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cmd/aws-explorer.exe
        asset_name: aws-explorer.exe
        asset_content_type: application/octet-stream


